import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Header from '../komponen/Header';
import Image from 'next/image';

export default function Home() {
  return (
    
    <div className={styles.container}>
      <Head>
        <title>kv</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className={styles.bundar}></div>

      <div className={styles.circle}>
        <div className={styles.ho1}>
          <div className={styles.co}></div>
        </div>
      </div>

      <div className={styles.ho}>
        <Image src="/ho.svg" alt='picture' width={800} height={650}></Image>
      </div>

      <div className={styles.text}>
        <h3>hello,iam</h3>
        <h2>AKMAL</h2>
        <p>Frontend developer 2 years experience sketching,building and<br></br>
        playfun. i love UI, collaboration and making helpful<br></br>
        products connect that people.</p>
      </div>

      <div className={styles.container2}>
        <div className={styles.frame_ux}>
          <div className={styles.ux}>
            <h2>UI</h2>
            <h1>/</h1>
            <h3>UX</h3>
            <button>UI/UX Designer</button>
          </div>
        </div>

        <div className={styles.frame_html}>
          <div className={styles.html}>
            <div className={styles.image}>
              <Image className={styles.image} src="/html.png" alt='picture' width={90} height={80}></Image>
            </div>

            <div className={styles.image1}>
              <Image className={styles.image1}src="/css.png" alt='picture' width={70} height={85}></Image>
            </div>

            <button>HTML CSS</button>
          </div>
        </div>

        <div className={styles.frame_frontend}>
          <div className={styles.frontend}>
            <div className={styles.image2}>
              <Image src="/ux.svg" alt='picture' className="rounded-xl" width={360} height={190}></Image>
            </div>
            <button>Next JS Developer</button>
          </div>
        </div>
      </div>
    </div>
  )
}
